apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: z2m
  annotations:
    spec.ingressClassName: traefik

spec:
  rules:
    - http:
        paths:
          - path: /z2m
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  name: http
