apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-data
  namespace: z2m
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
