apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
  namespace: default
  annotations:
    kuberenetes.io/ingress.class: "traefik"

spec:
  rules:
    - http:
        paths:
          - path: /todo
            backend:
              service:
                name: todo
                port:
                  number: 80
