apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ezbookkeeping-traefik
  namespace: ezbookkeeping
  annotations:
    spec.ingressClassName: ezbookkeeping
spec:
  rules:
    - host: ezbook.home.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ezbookkeeping
                port:
                  name: http
