apiVersion: v1
kind: ConfigMap
metadata:
  name: maybe-config
  namespace: maybe
data:
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: db
  DB_PORT: "5432"
  REDIS_URL: redis://redis:6379/1
  PGDATA: /var/lib/postgresql/data/pgdata
