apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tailscale
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tailscale
    spec:
      containers:
        - image: tailscale/tailscale:v1.80.0
          name: tailscale
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            privileged: true
          resources: {}
status: {}
