apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budge-traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: budge.10.0.0.103.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budge
                port:
                  number: 80
  tls:
    - hosts:
        - budge.your-traefik-domain.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budge-tailscale
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budge
                port:
                  number: 80
  tls:
    - hosts:
        - budge.deer-truck.ts.net
