apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budge-traefik
  namespace: budge
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - host: budge.10.0.0.103.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budge
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budge-tailscale
  namespace: budge
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budge
                port:
                  number: 80
  tls:
    - hosts:
        - budge.deer-truck.ts.net
