apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budge-pvc
  namespace: budge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
