apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Home
        # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
        # hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 12h
                feeds:
                  - url: https://selfh.st/rss/
                    title: selfh.st
                    limit: 4
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - j_blow
                  - piratesoftware
                  - cohhcarnage
          - size: full
            widgets:
              - type: search
                search-engine: https://search.brave.com/search?q={QUERY}
                autofocus: true

              - type: split-column
                widgets:
                  - type: monitor
                    cache: 1m
                    title: Apps
                    sites:
                      - title: Home Assistant
                        url: http://home.10.0.0.103.nip.io/
                        icon: si:homeassistant
                      - title: AdGuard Home
                        url: http://adguard.10.0.0.103.nip.io/
                        icon: si:adguard
                  - type: monitor
                    cache: 1m
                    title: Maintenance
                    sites:
                      - title: Uptime Kuma
                        url: http://uptime.10.0.0.103.nip.io/
                        icon: si:uptimekuma
                      - title: Traefik
                        url: http://traefik.10.0.0.103.nip.io/dashboard/
                        icon: si:traefikproxy
                      - title: Headlamp
                        url: http://monitor.10.0.0.103.nip.io/
                        icon: si:kubernetes
              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

              - type: videos
                channels:
                  - UCUyeluBRhGPCW4rPe_UvBZQ # ThePrimeTime
                  - UCpHDppEe092QBhOtSxJTMqw # Early Morning Dev
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship

              - type: group
                widgets:
                  - type: reddit
                    subreddit: webdev
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                  - type: reddit
                    subreddit: homeassistant
                    show-thumbnails: true

          - size: small
            widgets:
              - type: weather
                location: Oslo, Norway
                units: metric 
                hour-format: 24h # alternatively "24h"
                # Optionally hide the location from being displayed in the widget
                # hide-location: true

              - type: markets
                # The link to go to when clicking on the symbol in the UI,
                # {SYMBOL} will be substituded with the symbol for each market
                symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
                markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: QQQ
                    name: NASDAQ 100
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: OSL-DNB
                    name: DNB
                  - symbol: OSL-KOG
                    name: Kongsberg

              # - type: releases
              #   cache: 1d
              #   # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              #   # read-only token from your Github account settings and use it here to increase the limit.
              #   # token: ...
              #   repositories:
              #     - glanceapp/glance
              #     - go-gitea/gitea
              #     - immich-app/immich
              #     - syncthing/syncthing

      # Add more pages here:
      # - name: Your page name
      #   columns:
      #     - size: small
      #       widgets:
      #         # Add widgets here

      #     - size: full
      #       widgets:
      #         # Add widgets here

      #     - size: small
      #       widgets:
      #         # Add widgets here
