apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Home
        # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
        # hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 12h
                feeds:
                  - url: https://selfh.st/rss/
                    title: selfh.st
                    limit: 4
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed


          - size: full
            widgets:
              - type: search
                search-engine: https://search.brave.com/search?q={QUERY}
                autofocus: true

              - type: split-column
                widgets:
                  - type: monitor
                    cache: 1m
                    title: Apps
                    sites:
                      - title: Home Assistant
                        url: http://assistant.home.local/
                        check-url: http://10.0.0.132:8123/
                        icon: si:homeassistant
                      - title: AdGuard Home
                        url: http://adguard.home.local/
                        check-url: http://10.0.0.132:8123/
                        icon: si:adguard
                      - title: Actual Budget
                        url: http://actual.home.local/
                        icon: si:actualbudget
                      - title: Jellyfin
                        url: http://10.0.0.132:8096/
                        icon: si:jellyfin
                      - title: Sure
                        url: http://10.0.0.107:3000/
                        icon: sh:sure-finance
                      - title: N8n
                        url: http://10.0.0.92:5678/
                        icon: si:n8n
                  - type: monitor
                    cache: 1m
                    title: Content
                    sites:
                      - title: qBittorrent
                        url: http://homeassistant.local:8081/
                        check-url: http://10.0.0.132:8081/
                        icon: si:qbittorrent
                      - title: Jellyseer
                        url: http://10.0.0.132:5055
                        icon: sh:jellyseerr
                      - title: Prowlarr
                        url: http://10.0.0.132:9696
                        icon: sh:prowlarr
                      - title: Radarr
                        url: http://10.0.0.132:7878
                        icon: sh:radarr
                      - title: Sonarr
                        url: http://10.0.0.132:8989
                        icon: sh:sonarr
                      - title: LazyLibrarian
                        url: http://10.0.0.110:5299/
                        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/lazylibrarian.webp
                  - type: monitor
                    cache: 1m
                    title: Maintenance
                    sites:
                      - title: Uptime Kuma
                        url: http://uptime.home.local/
                        icon: si:uptimekuma
                      - title: Open Media Vault 
                        url: http://omv.local/
                        icon: si:openmediavault
                      - title: NAS
                        url: http://10.0.0.55/
                        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/ugreen-nas.svg
              - type: videos
                channels:
                  - UCUyeluBRhGPCW4rPe_UvBZQ # ThePrimeTime
                  - UCpHDppEe092QBhOtSxJTMqw # Early Morning Dev
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCyU5wkjgQYGRB0hIHMwm2Sg # Syntax.fm
                  - UCFvPgPdb_emE_bpMZq6hmJQ # Ben Davis
                  - UCo71RUe6DX4w-Vd47rFLXPg # typecraft
                  - UC4E2FSKc5czySVKqdsoR26A # TerminalShop
                  - UCkRbLkvUX5zuwnKOBwFHOjg # Mark builds brands

              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

              - type: group
                widgets:
                  - type: reddit
                    subreddit: webdev
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                  - type: reddit
                    subreddit: homeassistant
                    show-thumbnails: true

          - size: small
            widgets:
              - type: weather
                location: Oslo, Norway
                units: metric
                hour-format: 24h # alternatively "24h"
                # Optionally hide the location from being displayed in the widget
                # hide-location: true

              - type: markets
                # The link to go to when clicking on the symbol in the UI,
                # {SYMBOL} will be substituded with the symbol for each market
                symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
                markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: QQQ
                    name: NASDAQ 100
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: DNB.OL
                    name: DNB
                  - symbol: KOG.OL
                    name: Kongsberg Gruppen
                  - symbol: NOD.OL
                    name: Nordic Semiconductor

              # - type: releases
              #   cache: 1d
              #   # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              #   # read-only token from your Github account settings and use it here to increase the limit.
              #   # token: ...
              #   repositories:
              #     - glanceapp/glance
              #     - go-gitea/gitea
              #     - immich-app/immich
              #     - syncthing/syncthing

      # Add more pages here:
      # - name: Your page name
      #   columns:
      #     - size: small
      #       widgets:
      #         # Add widgets here

      #     - size: full
      #       widgets:
      #         # Add widgets here

      #     - size: small
      #       widgets:
      #         # Add widgets here
