apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    spec.ingressClassName: traefik

spec:
  defaultBackend:
    service:
      name: glance
      port:
        number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-tailscale
  namespace: glance
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - deer-truck.ts.net
  defaultBackend:
    service:
      name: glance
      port:
        number: 8080
