apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expenseowl-pvc
  namespace: expenseowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
