apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    spec.ingressClassName: traefik

spec:
  rules:
    - host: 10.0.0.103.nip.io
      http:
        paths:
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
