apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    spec.ingressClassName: traefik

spec:
  rules:
    - host: home.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
    - host: homelab.local
      http:
        paths:
          - path: /home-assistant
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
    - host: home.bartektelechome.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-tailscale
  namespace: home-assistant
  annotations:
    spec.ingressClassName: tailscale
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - home.deer-truck.ts.net
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
