apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
  namespace: actual
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
