apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adguard
  name: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adguard
    spec:
      containers:
        - image: adguard/adguardhome:v0.107.57
          name: adguard
          ports:
            - containerPort: 3000
              name: http-initial
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: adguard-config
            - mountPath: /opt/adguardhome/work
              name: adguard-data
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-data
        - name: adguard-config
          persistentVolumeClaim:
            claimName: adguard-config
status: {}
