apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  selector:
    app: adguard
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: 443
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
