apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adguard
  name: adguard
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-initial
  selector:
    app: adguard
  type: LoadBalancer
status:
  loadBalancer: {}
