apiVersion: v2
name: tailscale
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: tailscale-operator
    condition: tailscale-operator
    repository: https://pkgs.tailscale.com/helmcharts
    version: 1.80.3
