apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: home-assistant
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: home-assistant
    spec:
      containers:
        - image: docker.io/homeassistant/home-assistant:2025.2
          name: home-assistant
          env:
            - name: "PYTHONPATH"
              value: "/config/deps"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
            privileged: true
          ports:
            - containerPort: 8123
          resources: {}
status: {}
