apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: home-assistant
  name: home-assistant
  namespace: home-assistant
spec:
  ports:
    - name: 8123-8123
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer
status:
  loadBalancer: {}
