apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    per_listener_settings true

    log_dest stdout

    listener 8883
    protocol mqtt

    allow_anonymous false
    password_file /mosquitto/config/password.txt
  password.txt: |
    mqtt-admin:$7$101$hdjaQ6zchKuc3mIl$18Rd9BdckLHu+PPsqEHDtX2zSK7USL8rc2QpR38djjty4sV2InvoDmeFIb8hUJdbMiiyu32gIl6XUZDeym/0gQ==
