apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    per_listener_settings true

    log_dest stdout

    listener 8883
    protocol mqtt

    allow_anonymous false
    password_file /mosquitto/config/password.txt
  password.txt: |
    admin:$7$101$rvrOeXo8IjDJF8aG$nOliJX11sYPCpyddDDGSM3flczHp7Z9iA5EFpg0J79K+eFAS3pEs4ldLXBb60u4tOe/BoYhzmRQDf9/5s56KJQ==
